### ISSUE TITLE
New RPCs: `bootstrap`, `connectshardpeer`, `identify`

### ISSUE THREAD

**Issue by mhchia** [ethresearch/sharding-p2p-poc#108]
### What is wrong?
- `bootstrap`
    - `bootstrap start`: start the dht bootstrapping process
    - `bootstrap stop`: stop the dht bootstrapping process
- `connectshardpeer {shardID}`: connect to the peers discovered in the shard
- `identify`: list the node's `peer_id` and `multiaddrs`

**Comment by mhchia** [comment]
`identify.peerID` is included in https://github.com/ethresearch/sharding-p2p-poc/issues/108

**Comment by NIC619** [comment]
Regarding `connectshardpeer`, do we need a full control over how topology is constructed? Perhaps to test some edge cases? cc @mhchia @zscole 
If not, what about instead connecting to randomly selected `k` shard peers when we subscribe to a new shard?
Or randomly selected `k` shard peers by default while adding a `-dontAddPeer` flag to instruct the node to not add peers when subscribing to a new shard?

**Comment by NIC619** [comment]
> that seems useful but might also introduce a vulnerability as bad actors can collude and start their own shard and broadcast bad information
no plans on peering with those peers discovered from that shard_id?

So `-nodiscover` and `discover shard_id` are only for testing purpose(in case we want to construct the topology in our favor by manually adding peers from the shard). Normal user would just subscribe to a new shard and randomly connect to `k` peers.

Regarding randomization, it will not be like how we generate our node's private key. We need determinism in generating our node's private key because it makes testing easier(i.e., we can be sure that feeding with seed `1` would generate the key pair that's encoded into PID `XtW5fX ` for example.)

For the randomization used in `connectShardNodes`, the entropy is probably fetched from the machine's local environment etc. instead of being fed by us.

**Comment by mhchia** [comment]
Fixed by https://github.com/ethresearch/sharding-p2p-poc/pull/131
